### ISSUE TITLE
Problem during install.

### ISSUE THREAD

**Issue by ruzzzz6312** [soulman-is-good/node-ssp#3]
npm install ssp

node-pre-gyp http 404 https://github.com/voodootikigod/node-serialport/releases/download/3.2.0-beta1/serialport-v3.2.0-beta1-node-v11-linux-ia32.tar.gz
node-pre-gyp ERR! Tried to download: https://github.com/voodootikigod/node-serialport/releases/download/3.2.0-beta1/serialport-v3.2.0-beta1-node-v11-linux-ia32.tar.gz 

Thanks

**Comment by Vandalko** [comment]
Try to prune your dependencies and reinstall.
Because you have the problem with one of them:
https://github.com/soulman-is-good/node-ssp/blob/master/package.json#L33

You can manually install latest 3.x version : https://github.com/EmergingTechnologyAdvisors/node-serialport/blob/3.1.2/README.md

**Comment by ruzzzz6312** [comment]
@Vandalko can we privately email please?
616312@gmail.com
